apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: web
  name: web-pvc-uploads
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
  volumeMode: Filesystem